### ISSUE TITLE
Dota.api.teams(id) return wrong data

### ISSUE THREAD

**Issue by pihao** [vinnicc/dota#31]
If you try to get a team that has been disbanded. For example: `2243650`:

    Dota.api.teams(2243650).id

You'll get `2243651`, not `2243650`.

But you can get the right data with below api:

    Dota.api.get("IDOTA2Teams_570", "GetTeamInfo", team_id: 2243650)

And you'll see `"disbanded"=>true`.

**Comment by vinnicc** [comment]
Confirming this, but I'm unable to switch `Client#teams` to use `GetTeamInfo` instead of `GetTeamInfoByTeamID` without breaking the existing API. I'm open to bump the version with these corrections though. It's just tedious with the lack of official documentation that can be used as a contract.

Will keep this issue open for a while in case other people can offer a solution. PRs are welcome!

**Comment by pihao** [comment]
How about this:
Return `nil` when the result ID is not equal with parameter ID. Because really not find the team of the specify ID.

**Comment by vinnicc** [comment]
@pihao Fixed, thanks!
